version: '3.8'
services:
  node:
    container_name: node-api
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5000:5432'
    volumes:
      - pg:/var/lib/postgresql/data
# Names our volume
volumes:
  pg:
